# Generated by Django 5.1.7 on 2025-07-03 22:45

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrouselBanner_name', models.CharField(max_length=30)),
                ('carrouselBanner_descripcion', models.CharField(max_length=300)),
                ('carrouselBanner_url_img', models.ImageField(null=True, upload_to='Imagenes_CarrouselBanner')),
                ('statusBanner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_name', models.CharField(max_length=30)),
                ('categoria_descripcion', models.CharField(max_length=300)),
                ('categoria_url_img', models.ImageField(null=True, upload_to='Imagenes_Categoria')),
                ('statusCategoria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=30)),
                ('empresa_descripcion', models.TextField(max_length=300)),
                ('empresa_logo', models.ImageField(null=True, upload_to='Imagenes_Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_name', models.CharField(max_length=30)),
                ('marca_url_img', models.ImageField(null=True, upload_to='Imagenes_Marca')),
                ('status', models.BooleanField(default=True)),
                ('marca_descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_nombre', models.CharField(max_length=50)),
                ('proyecto_descripcion_corta', models.TextField(max_length=500)),
                ('proyecto_descripcion_larga', models.TextField(max_length=2000)),
                ('proyecto_imagen', models.ImageField(null=True, upload_to='Imagenes_Proyecto')),
                ('proyecto_imagen_banner', models.ImageField(null=True, upload_to='Imagenes_Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_nombre', models.CharField(max_length=50)),
                ('servicio_descripcion', models.TextField(max_length=500)),
                ('servicio_imagen', models.ImageField(null=True, upload_to='Imagenes_Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda_enlace', models.URLField()),
                ('tienda_nombre', models.CharField(max_length=30)),
                ('tienda_descripcion', models.TextField(max_length=300)),
                ('tienda_imagen', models.ImageField(upload_to='Imagenes_Tienda/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen_nombre', models.CharField(max_length=30)),
                ('almacen_direccion_calle', models.CharField(max_length=300)),
                ('almacen_direccion_numero', models.CharField(max_length=30)),
                ('almacen_direccion_colonia', models.CharField(max_length=30)),
                ('almacen_direccion_cp', models.CharField(max_length=30)),
                ('almacen_direccion_ciudad', models.CharField(max_length=30)),
                ('almacen_direccion_estado', models.CharField(max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abv_web.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_extendido', models.CharField(max_length=30)),
                ('producto_sku', models.CharField(max_length=30)),
                ('producto_skunetsuite', models.CharField(default='', max_length=300)),
                ('producto_ean', models.CharField(max_length=30)),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('producto_modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('producto_precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto_precio_amazon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto_precio_mercadolibre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto_precio_ebay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto_url_img', models.ImageField(null=True, upload_to='Imagenes_Producto')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abv_web.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abv_web.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abv_web.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abv_web.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSecundariaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_secundaria', models.ImageField(null=True, upload_to='Imagenes_Producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abv_web.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entry', to='abv_web.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entry', to='abv_web.proyecto')),
            ],
        ),
    ]
